const menuList = [
    {
        title:'首页',
        key:'/admin/home'
    },
    {
        title:'UI',
        key:'/admin/ui',
        children:[
            {
                title:'按钮',
                key:'/admin/ui/buttons'
            },
            {
                title:'弹窗',
                key:'/admin/ui/modals'
            },
            {
                title:'Loading',
                key:'/admin/ui/loading'
            },
            {
                title:'通知提醒',
                key:'/admin/ui/notification'
            },
            {
                title:'全局通知',
                key:'/admin/ui/message'
            },
            {
                title:'tab标签页',
                key:'/admin/ui/tabs'
            },
            {
                title:'图片画廊',
                key:'/admin/ui/gallery'
            },
            {
                title:'轮播图',
                key:'/admin/ui/carousel'
            }
        ]
    },
    {
        title:'表单',
        key:'/admin/form',
        children:[
            {
                title:'登录',
                key:'/admin/form/login'
            },
            {
                title:'注册',
                key:'/admin/form/register'
            },
            {
                title:'函数组件表单',
                key:'/admin/form/funcForm'
            },
        ]
    },
    {
        title:'表格',
        key:'/admin/table',
        children:[
            {
                title:'基本表单',
                key:'/admin/table/basic'
            },
            {
                title:'高级表单',
                key:'/admin/table/senior'
            }
        ]
    }
];
export default menuList;
